{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "bluegreen.serviceAccountName" . }}
  labels:
{{ include "bluegreen.labels" . | indent 4 }}
{{- end -}}
