apiVersion: v1
kind: Service
metadata:
  name: {{ include "bluegreen.fullname" . }}-active
  labels:
{{ include "bluegreen.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      #targetPort: http
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    #app: {{ include "bluegreen.name" . }}
    app.kubernetes.io/name: {{ include "bluegreen.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bluegreen.fullname" . }}-preview
  labels:
{{ include "bluegreen.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    #app: {{ include "bluegreen.name" . }}
    app.kubernetes.io/name: {{ include "bluegreen.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
